file_sharing_project/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sharing_app.urls')),
    path('user/', include('user_app.urls')),


]

# path('reg/', user_views.registration, name="registration"),
#  path('reg/', include('user_app.urls')),
# for user app: welcome -> registration
#                       -> login

sharing_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

# This app name is important as reverse function looks for this to create an url.
app_name = 'sharing_app'

urlpatterns = [
    path('',views.home, name="home"),
    path('upload/', views.upload, name="upload"),
    path('download/<int:file_id>/', views.download, name="download"), # <int:filename>/ gets the file primary id to download.
    path('share/<int:file_id>/', views.share, name="share"),

    #path('share_file/', views.share_file, name='share_file'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app name: (user for reverse and routing in html files)
app_name = 'user_app'

urlpatterns = [
   path('reg/', views.registration, name="registration"),
   path('login/', auth_views.LoginView.as_view(template_name='user/loginMub.html'), name="login"),
   #path('login/', auth_views.LogoutView.as_view(template_name='user/loginMub.html'), name="logout"),
   path('', auth_views.LogoutView.as_view(), name="logout"),
   path('profile/', views.profile, name="profile"),

]

templates/share/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>User Files</title>
</head>
<body>

    {% if user.is_authenticated %}

        <h1>User Files</h1><br>
        <a href="{% url 'user_app:logout'%}"> Log out</a> <br>
        <a href="{% url 'user_app:profile'%}"> Profile</a> <br>
        <a href="{% url 'sharing_app:upload'%}"> Upload</a> <br>

        {% if user_files %}
            <ul>
                {% for file in user_files %}
                    <li>
                        <strong>File Name:</strong> {{ file.fileName }}
                        <br>
                        <strong>File Size:</strong> {{ file.fileSize }} mb
                        <br>
                        {# We can download the file using the .url but it will be encrypted. #}
                        {# <strong><a href="{{ file.fileDir.url }}"> Download file </a></strong> #}
                        {# we are passing file id here that is clicked. file is from the datbase.#}
                        <a href="{% url 'sharing_app:download' file_id=file.id %}"> Download File </a><br>
                        <a href="{% url 'sharing_app:share' file_id=file.id %}"> Share File </a>
                        <br><br>
                    </li>
                {% endfor %}
            </ul>

        {% else %}
            <p>No files uploaded yet.</p>
        {% endif %}

    {% else %}

            <h1> Login or Sign in</h1>
            <a href="{% url 'user_app:login' %}"> log in</a>
            <a href="{% url 'user_app:registration' %}"> sign up</a>

    {% endif %}
    
</body>
</html>

templates/share/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Bootstrap CSS link -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="/static/user/homeAbhi.css?v=2">
</head>

<body>

    <div class="navbar">
        <div class="logo">File Share</div>
        <ul class="nav-list">
            <li><a href="{% url 'sharing_app:upload'%}">Upload File</a></li>
            <li><a href="{% url 'user_app:profile'%}">Profile</a></li>
            <li><a href="{% url 'user_app:logout'%}">Logout</a></li>
        </ul>
    </div>
    
    <!-- Bootstrap Navbar -->
    <!-- <nav class="navbar navbar-expand-lg navbar-white " id="navbarhas"> -->
        <!-- Replace "Navbar" with "FILE SHARE" -->
        <!-- <div>
            <a class="navbar-brand" href="#">FILE SHARE</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item_welcome"><a class="nav-link">Welcome, {{user.username}}</a></li>
                <li class="nav-item_logout"><a class="nav-link" href="{% url 'sharing_app:upload'%}">Upload Files</a></li>
                <li class="nav-item_logout"><a class="nav-link" href="{% url 'user_app:profile'%}">Profile</a></li>
                <li class="nav-item_logout"><a class="nav-link" href="{% url 'user_app:logout'%}">Logout</a></li>
            </ul>
        </div>
    </nav> -->

    <!-- Bootstrap JavaScript and Popper.js -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->

    <div class="border-example">
        <h5 class="head1">UPLOADED FILES</h5>
        <div class="para">
            {% if user_files %}
                <ul>
                    {% for file in user_files %}
                        {% if not file.shared %}

                            <div class="file-info">
                                <strong style="color:rgb(255, 255, 255)">File Name:  {{ file.fileName }} </strong>
                                <strong style="color:rgb(255, 255, 255)">File Size: {{ file.fileSize }} mb </strong> 
                            </div>
                            <div class="action-buttons">
                                <a class="share-down" href="{% url 'sharing_app:download' file_id=file.id %}" style="color: rgb(34, 216, 156);" class="dw1">DOWNLOAD</a>
                                <a class="share-down" href="{% url 'sharing_app:share' file_id=file.id %}" style="color: rgb(95, 152, 133);" class="dw1">SHARE</a>
                            </div>
                            <br><br>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% else %}
                <p>No files uploaded yet.</p>
            {% endif %}


        </div>
    </div>


    <div class="border2">
        <p class="head2">SHARED FILES</p>
        <div class="para2">
            {% if user_files %}
                <ul>
                    {% for file in user_files %}
                        {% if file.shared %}

                            <div class="file-info">
                                <strong style="color:rgb(255, 255, 255)">File Name:  {{ file.fileName }} </strong>
                                <strong style="color:rgb(255, 255, 255)">File Size: {{ file.fileSize }} mb </strong> 
                                <strong style="color:rgb(255, 255, 255)">Sender: {{ file.sender }} </strong> 
                            </div>
                            <div class="action-buttons" id="sh-do-has">
                                <a class="share-down" href="{% url 'sharing_app:download' file_id=file.id %}" style="color: rgb(34, 216, 156);" class="dw1">DOWNLOAD</a>
                                <a class="share-down" href="{% url 'sharing_app:share' file_id=file.id %}" style="color: rgb(95, 152, 133);" class="dw1">SHARE</a>
                            </div>
                            <br><br>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% else %}
                <p>No files SHared yet.</p>
            {% endif %}

        </div>
    </div> 

</body>

</html>

templates/share/profile.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Portfolio</title>
    <link rel="stylesheet" type="text/css" href="/static/user/profileAbhi.css?v=2">
  </head>
  <body>
    

      <nav>
        <h1 class="heading1">HOMEPAGE</h1>
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </nav>
      <h2 class="head2">This is a File Share Portal, You can upload files to cloud or share with your friends</h2>
    <main>
      <h2 class="heading2">SIGN IN IF YOU HAVE AN ACCOUNT</h2>
      <button class="button1" onclick="location.href='signin.html'">Sign in</button>
      <h2 class="heading3">DONT HAVE AND ACCOUNT?
        PLEASE SIGN UP.
      </h2>
      <button class="button2" onclick="location.href='signup.html'">Sign up</button>
    </main>
   
  </body>
</html>

templates/share/profilePage.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Profile Page</title>
    <link rel="stylesheet" href="/static/user/profilePage.css?=2">
</head>

<body>
    <div class="navbar">
        <div class="logo">Profile Page</div>
        <ul class="nav-list">
            <li><a href="{% url 'sharing_app:home' %}">Home</a></li>
            <li><a href="{% url 'sharing_app:upload' %}">Upload File</a></li>
            <li><a href="{% url 'user_app:login' %}">Login</a></li>
            <li><a href="{% url 'user_app:logout' %}">Logout</a></li>
        </ul>
    </div>

    <div class="message">
        <p> <a style="color: aqua;">Welcome to your profile page!</a> Here is your profile information.</p>
    </div>

    <div class="user">
        <b><label for="firstname">User name: <a style="color: chocolate;">{{user.username}}</a> </label></b>
        <br>
        <b><label for="firstname">First Name: <a style="color: chocolate;">{{user.first_name}}</a> </label></b>
        <br>
        <b><label for="lastname">Last Name: <a style="color: chocolate;">{{user.last_name}}</a></label></b>
        <br>
        <b><label for="email">Email: <a style="color: chocolate;">{{user.email}}</a></label></b>
        <br>
        <br>
    </div>

</body>

</html>

templates/share/share.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>File Sharing</title>
    <link rel="stylesheet" href="/static/css/style.css">
<body>

    <div class="container">
        <h1>File Sharing</h1>


        <form method="post">
            {% csrf_token %}
            <!-- Remember name is used to connect with inputs and variable in function -->
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required> <br>

            <button type="submit">Share</button>
        </form>

        {% if errorMessage %}
            <script>
                alert("{{ errorMessage }}");
            </script>
        {% endif %}

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}



        <h2>Shared Files</h2>
        <ul>
            {% for file in shared_files %}
                <li>
            
                </li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>

templates/share/shareAmjd.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>File Sharing Page</title>
    <link rel="stylesheet" href="/static/user/shareMub.css">
</head>

<body>
    <div class="navbar">
        <div class="logo">File Share</div>
        <ul class="nav-list">
            <li><a href="{% url 'sharing_app:home' %}">Home</a></li>
            <li><a href="{% url 'sharing_app:upload'%}">Upload File</a></li>
            <li><a href="{% url 'user_app:profile'%}">Profile</a></li>
            <li><a href="{% url 'user_app:logout'%}">Logout</a></li>
        </ul>
    </div>

    <div class="receiver">
        <h1>Receiver</h1>
    </div>
    <form method="post">
        <div class="user">

            {% csrf_token %}
            <label for="username">Username: </label>
            <input type="text" id="username" name="username" placeholder="Enter Username">
            <br>
            <br>
            <!-- <label for="share">To share a file: </label> -->
            <button type="submit" id="share" name="share">Share</button></b>


            {% if errorMessage %}
                <script>
                    alert("{{ errorMessage }}");
                </script>
            {% endif %}
        
            <!-- {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>
                            {% if message.tags %} 
                            
                            class="{{ message.tags }}" 

                            {% endif %}>{{ message }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %} -->
            
        </div>
    </form>


    <div class="file">
        <h1>File Description</h1>
    </div>

    <div class="file_info">
        <p>File Name: {{file_to_share.fileName}}</p>
        <br>
        <p>File Size: {{file_to_share.fileSize}} </p>
        <br>
        <!-- <p>File Type: </p>
        </b> -->
    </div>

</body>

</html>

templates/share/upload.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <title>File Upload</title>
        <link rel="stylesheet" href="/static/user/register.css?v=2">
    </head>
    <body>
        <h1>Upload a File</h1>
        <form method="post" enctype="multipart/form-data"">
            {% csrf_token %}
            <div>

                {{form}}
            <br>
            <button type="submit">Upload</button>
        </form>
        <a href="{% url 'user_app:logout'%}"> Log out</a> <br>
        <a href="{% url 'user_app:profile'%}"> Profile</a> <br>
        <a href="{% url 'sharing_app:home'%}"> home</a> <br>

    </body>
</html>

templates/share/uploadAmjd.html
<!DOCTYPE html>
<html>
    <head>
   
        <title>Upload Page</title>
        <link rel="stylesheet" type="text/css" href="/static/user/uploadMub.css?v=2">

    </head>
    <body>

        <div class="navbar">
            <div class="logo">File Share</div>
            <ul class="nav-list">
                <li><a href="{% url 'sharing_app:home' %}">Home</a></li>
                <li><a href="{% url 'user_app:profile' %}">Profile</a></li>
                <li><a href="{% url 'user_app:logout' %}">Logout</a></li>
            </ul>
        </div>
        

        <div class="container">
            <h1> Upload</h1>
            <div class="box">
                <div id="fieldHasn">
                    <form id="fileNameForm" method="POST" enctype="multipart/form-data">

                        {% csrf_token %}
                    <!-- remember name == the field names in form -->
                        <!-- {{ form.fileName.label_tag }}
                        <input type="text" id="{{ form.fileName.id_for_label }}" name="{{ form.fileName.name }}" required>
                        {% if form.fileName.errors %}
                            <p class="error">{{ form.fileName.errors }}</p>
                        {% endif %}

                        {{ form.fileDir.label_tag }}
                        <input type="file" id="{{ form.fileDir.id_for_label }}" name="{{ form.fileDir.name }}" required>
                        {% if form.fileDir.errors %}
                            <p class="error">{{ form.fileDir.errors }}</p>
                        {% endif %} -->
                        {{form}}
                    
                        <input class="submit" type="submit" value="Upload">
                    </form>
                </div>
                
                <!-- <style>
                .register {
                    margin: 300px 0px 0px 130px;

                }
            
                .reg {
                    color: #3498db;
                    text-decoration: none;
                    font-weight: bold;
                }
            
                .reg:hover {
                    text-decoration: underline;
                }
                </style>
            
                <div class="register">
                    <span style="color: rgb(255, 255, 255);">Click <a class="reg" href="{% url 'sharing_app:home' %}">Home</a> to go back.</span>
                </div> -->
            </div>
    </body>
</html>



